version: '3.7'

services:
  service-a:
    build:
      context: .
    restart: always

  service-b:
    build:
      context: .
    restart: always

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 5000:80
    depends_on:
      - service-a
      - service-b
