# Note: ci.yaml and release.yaml have some similar steps
#       If updating dotnet-version, set in both.

name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x' # SDK Version to use; x will use the latest version of the channel
    - name: Run dotnet build
      run: dotnet build --configuration Debug
    - name: Run dotnet test
      run: dotnet test --no-build
